server:
  port: 8080 #¶Ë¿ÚºÅ

spring:
  datasource:
    username:  www_sciencewithf
    password:  d4eRWnFCm7ZcG2KN
    url: jdbc:mysql://localhost:3306/timeapp?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath:Mapper/*.xml
  type-aliases-package: com.example.entity

#showSql
logging:
  level:
    com:
      example:
        mapper: debug

absoluteImgPath : /www/time_app_img/
sonImgPath : /time_app_img/